window:
  dynamic_title: true
  history: 100000
font:
  normal:
    family: Source Code Pro
  size: 10.0
colors:
  primary:
    background: '#101010'
    foreground: '#f8f8f2'
  normal:
    black:   '#272822'
    red:     '#f92672'
    green:   '#a6e22e'
    yellow:  '#f4bf75'
    blue:    '#66d9ef'
    magenta: '#ae81ff'
    cyan:    '#a1efe4'
    white:   '#f9f8f5'
cursor:
  style:
    blinking: On
  blink_interval: 600
